### ISSUE TITLE
Gpu mortgage notebook failure in Databricks

### ISSUE THREAD

**Issue by sauravdev** [NVIDIA/spark-xgboost-examples#36]
**Describe the bug**
While running the mortgage notebook in https://github.com/NVIDIA/spark-xgboost-examples/blob/spark-3/examples/notebooks/python/mortgage-gpu.ipynb
Error: Method setFeaturesCols([class scala.collection.convert.Wrappers$JListWrapper]) does not exist

**Steps/Code to reproduce bug**

 Followed steps mentioned here to Setup https://github.com/NVIDIA/spark-xgboost-examples/tree/spark-3/getting-started-guides/csp/databricks

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: Databricks 7.3 LTS ML Runtime  
 - Spark configuration settings related to the issue
 spark.plugins com.nvidia.spark.SQLPlugin
spark.task.resource.gpu.amount 0.1
spark.locality.wait 0s
spark.databricks.delta.optimizeWrite.enabled false
spark.sql.adaptive.enabled false
spark.rapids.sql.concurrentGpuTasks 2

**Comment by GaryShen2008** [comment]
Seems xgboost jar not loaded.
I'll try it tomorrow to see what happened.

**Comment by GaryShen2008** [comment]
@sauravdev 
Could you please share more details because I succeeded to run on Azure Databricks?

Here's my testing environment.
Cluster mode: Standard
Databricks Runtime Version: 7.3 LTS ML (includes Apache Spark 3.0.1, GPU, Scala 2.12)

Spark Config
spark.plugins com.nvidia.spark.SQLPlugin
spark.task.resource.gpu.amount 0.1
spark.locality.wait 0s
spark.databricks.delta.optimizeWrite.enabled false
spark.sql.adaptive.enabled false
spark.rapids.sql.concurrentGpuTasks 2

InitScript:
DBFS
dbfs:/databricks/init_scripts/init.sh
#!/bin/bash
sudo cp /dbfs/FileStore/jars/xgboost4j_3.0-1.3.0-0.1.0.jar /databricks/jars/spark--maven-trees--ml--7.x--xgboost--ml.dmlc--xgboost4j_2.12--ml.dmlc__xgboost4j_2.12__1.0.0.jar
sudo cp /dbfs/FileStore/jars/cudf-0.18.1.jar /databricks/jars/
sudo cp /dbfs/FileStore/jars/rapids-4-spark_2.12-0.4.1.jar /databricks/jars/
sudo cp /dbfs/FileStore/jars/xgboost4j-spark_3.0-1.3.0-0.1.0.jar /databricks/jars/spark--maven-trees--ml--7.x--xgboost--ml.dmlc--xgboost4j-spark_2.12--ml.dmlc__xgboost4j-spark_2.12__1.0.0.jar

**Comment by GaryShen2008** [comment]
After talking to sauravdev on slack, he succeeded to run.
Seems he didn't follow the steps to download the xgboost jars and restart the cluster.
Closed the issue.
